spring.application.name=backend

server.port=8080

# MySQL settings
spring.datasource.url=jdbc:mysql://localhost:3306/vote?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jackson.default-property-inclusion=non_null
